### ISSUE TITLE
Crashes on Spotify

### ISSUE THREAD

**Issue by andrewshadura** [i-rinat/freshplayerplugin#133]
Opening https://play.spotify.com/ crashes the plugin immediately.

   plugin-containe[1981] segfault at 74890828 ip b7792bd9 sp acd219c0 error 4 in ld-2.19.so[b7785000+1f000]

**Comment by andrewshadura** [comment]
```
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0xacd23b40 (LWP 2017)]
_dl_fixup (l=0xaebe10f4, reloc_arg=2890661920) at dl-runtime.c:69
69	dl-runtime.c: No such file or directory.
(gdb) bt full
#0  _dl_fixup (l=0xaebe10f4, reloc_arg=2890661920) at dl-runtime.c:69
        symtab = <optimized out>
        strtab = <optimized out>
        reloc = <optimized out>
        sym = 0xae372af0
        rel_addr = <optimized out>
        result = <optimized out>
        value = <optimized out>
        __PRETTY_FUNCTION__ = "_dl_fixup"
#1  0xb772a020 in _dl_runtime_resolve () at ../sysdeps/i386/dl-trampoline.S:36
No locals.
#2  0xab88e000 in ?? ()
No symbol table info available.
#3  0xaebe16ab in ?? () from /usr/lib/pepperflashplugin-nonfree/libpepflashplayer.so
No symbol table info available.
#4  0xaebe258b in ?? () from /usr/lib/pepperflashplugin-nonfree/libpepflashplayer.so
No symbol table info available.
#5  0xaebe3e51 in ?? () from /usr/lib/pepperflashplugin-nonfree/libpepflashplayer.so
No symbol table info available.
#6  0xae458ada in ?? () from /usr/lib/pepperflashplugin-nonfree/libpepflashplayer.so
No symbol table info available.
#7  0xae458ba1 in ?? () from /usr/lib/pepperflashplugin-nonfree/libpepflashplayer.so
No symbol table info available.
#8  0xae459f47 in ?? () from /usr/lib/pepperflashplugin-nonfree/libpepflashplayer.so
No symbol table info available.
#9  0xae45a77d in ?? () from /usr/lib/pepperflashplugin-nonfree/libpepflashplayer.so
No symbol table info available.
#10 0xae45a817 in ?? () from /usr/lib/pepperflashplugin-nonfree/libpepflashplayer.so
No symbol table info available.
#11 0xae45b630 in ?? () from /usr/lib/pepperflashplugin-nonfree/libpepflashplayer.so
No symbol table info available.
#12 0xae45b6ea in ?? () from /usr/lib/pepperflashplugin-nonfree/libpepflashplayer.so
No symbol table info available.
#13 0xae443d1c in ?? () from /usr/lib/pepperflashplugin-nonfree/libpepflashplayer.so
No symbol table info available.
#14 0xac4e023f in ?? ()
---Type <return> to continue, or q <return> to quit---
No symbol table info available.
#15 0xac4deb6b in ?? ()
No symbol table info available.
#16 0xae3be540 in ?? () from /usr/lib/pepperflashplugin-nonfree/libpepflashplayer.so
No symbol table info available.
#17 0xae3d1012 in ?? () from /usr/lib/pepperflashplugin-nonfree/libpepflashplayer.so
No symbol table info available.
#18 0xae3bf065 in ?? () from /usr/lib/pepperflashplugin-nonfree/libpepflashplayer.so
No symbol table info available.
#19 0xae3a13d3 in ?? () from /usr/lib/pepperflashplugin-nonfree/libpepflashplayer.so
No symbol table info available.
#20 0xac4dedf7 in ?? ()
No symbol table info available.
#21 0xae3bbee5 in ?? () from /usr/lib/pepperflashplugin-nonfree/libpepflashplayer.so
No symbol table info available.
#22 0xae3bbd63 in ?? () from /usr/lib/pepperflashplugin-nonfree/libpepflashplayer.so
No symbol table info available.
#23 0xac4def30 in ?? ()
No symbol table info available.
#24 0xae3bc332 in ?? () from /usr/lib/pepperflashplugin-nonfree/libpepflashplayer.so
No symbol table info available.
#25 0xae3bd28e in ?? () from /usr/lib/pepperflashplugin-nonfree/libpepflashplayer.so
No symbol table info available.
#26 0xae3be133 in ?? () from /usr/lib/pepperflashplugin-nonfree/libpepflashplayer.so
No symbol table info available.
#27 0xae3bbe85 in ?? () from /usr/lib/pepperflashplugin-nonfree/libpepflashplayer.so
No symbol table info available.
#28 0xae3c0c2e in ?? () from /usr/lib/pepperflashplugin-nonfree/libpepflashplayer.so
No symbol table info available.
#29 0xae3c374b in ?? () from /usr/lib/pepperflashplugin-nonfree/libpepflashplayer.so
No symbol table info available.
#30 0xae3bcdfb in ?? () from /usr/lib/pepperflashplugin-nonfree/libpepflashplayer.so
No symbol table info available.
#31 0xae3bbe85 in ?? () from /usr/lib/pepperflashplugin-nonfree/libpepflashplayer.so
No symbol table info available.
#32 0xae51a942 in ?? () from /usr/lib/pepperflashplugin-nonfree/libpepflashplayer.so
---Type <return> to continue, or q <return> to quit---
No symbol table info available.
#33 0xae51aa80 in ?? () from /usr/lib/pepperflashplugin-nonfree/libpepflashplayer.so
No symbol table info available.
#34 0xae51adc1 in ?? () from /usr/lib/pepperflashplugin-nonfree/libpepflashplayer.so
No symbol table info available.
#35 0xae477345 in ?? () from /usr/lib/pepperflashplugin-nonfree/libpepflashplayer.so
No symbol table info available.
#36 0xae6efbe4 in ?? () from /usr/lib/pepperflashplugin-nonfree/libpepflashplayer.so
No symbol table info available.
#37 0xae6efdb3 in ?? () from /usr/lib/pepperflashplugin-nonfree/libpepflashplayer.so
No symbol table info available.
#38 0xae6f2672 in ?? () from /usr/lib/pepperflashplugin-nonfree/libpepflashplayer.so
No symbol table info available.
#39 0xae6f2bd5 in ?? () from /usr/lib/pepperflashplugin-nonfree/libpepflashplayer.so
No symbol table info available.
#40 0xae6f356a in ?? () from /usr/lib/pepperflashplugin-nonfree/libpepflashplayer.so
No symbol table info available.
#41 0xae6f57f8 in ?? () from /usr/lib/pepperflashplugin-nonfree/libpepflashplayer.so
No symbol table info available.
#42 0xae701314 in ?? () from /usr/lib/pepperflashplugin-nonfree/libpepflashplayer.so
No symbol table info available.
#43 0xae707bf4 in ?? () from /usr/lib/pepperflashplugin-nonfree/libpepflashplayer.so
No symbol table info available.
#44 0xae72f129 in ?? () from /usr/lib/pepperflashplugin-nonfree/libpepflashplayer.so
No symbol table info available.
#45 0xae76fdfc in ?? () from /usr/lib/pepperflashplugin-nonfree/libpepflashplayer.so
No symbol table info available.
#46 0xae31b5b0 in ?? () from /usr/lib/pepperflashplugin-nonfree/libpepflashplayer.so
No symbol table info available.
#47 0xae330470 in ?? () from /usr/lib/pepperflashplugin-nonfree/libpepflashplayer.so
No symbol table info available.
#48 0xae33098f in ?? () from /usr/lib/pepperflashplugin-nonfree/libpepflashplayer.so
No symbol table info available.
#49 0xae330782 in ?? () from /usr/lib/pepperflashplugin-nonfree/libpepflashplayer.so
No symbol table info available.
#50 0xb164e413 in ppb_message_loop_run_int (message_loop=2, flags=2890661920) at /tmp/freshplayerplugin/src/ppb_message_loop.c:315
---Type <return> to continue, or q <return> to quit---
        now = {tv_sec = 1422559074, tv_nsec = 98406314}
        __func__ = "ppb_message_loop_run_int"
        int_q = 0xab88e000
#51 0xb164e4fe in ppb_message_loop_run (message_loop=2) at /tmp/freshplayerplugin/src/ppb_message_loop.c:196
No locals.
#52 0xb163bd79 in fresh_wrapper_main_thread (p=0xae116cc0) at /tmp/freshplayerplugin/src/main_thread.c:58
        pp_i = 0xae116cc0
        message_loop = 2
        __func__ = "fresh_wrapper_main_thread"
#53 0xb76c0efb in start_thread (arg=0xacd23b40) at pthread_create.c:309
        __res = <optimized out>
        pd = 0xacd23b40
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {-1217581056, -1395508416, 4001536, -1395510680, 473435623, 1615265232}, mask_was_saved = 0}}, 
          priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#54 0xb30a1dfe in clone () at ../sysdeps/unix/sysv/linux/i386/clone.S:129
No locals.
```

**Comment by i-rinat** [comment]
It's very similar to what I see in #124. Can you check whenever PepperFlash works in Chrome on Spotify?

**Comment by ahjolinna** [comment]
works just fine for me, im using the -git version

**Comment by i-rinat** [comment]
This happens with 32-bit plugin, it crashes in Chrome too (at least on my machine), with the very similar backtrace. Something wrong happens on external link resolution time. 64-bit version of PepperFlash works fine though.

**Comment by i-rinat** [comment]
I've tried again, with PepperFlash updated to 16.0.0.305. And it now works fine with twich.tv. Unfortunately, Spotify is not available in Russia, so I can't check it.
