### ISSUE TITLE
plugin crash on deezer (ter)

### ISSUE THREAD

**Issue by kubrickfr** [i-rinat/freshplayerplugin#182]
New deezer crash issue with (using git rev c1bf8c442aa7ac2772a3d77692d665c1940d8b78)
Thread bt:
```
#0  0x000000000040ff90 in jemalloc_crash () at /usr/src/debug/firefox-37.0.2/mozilla-release/memory/mozjemalloc/jemalloc.c:1610
#1  0x0000000000411d19 in arena_dalloc (ptr=<optimized out>, offset=<optimized out>) at /usr/src/debug/firefox-37.0.2/mozilla-release/memory/mozjemalloc/jemalloc.c:4711
        chunk = <optimized out>
        arena = 0x7fa4fa600040
        pageind = <optimized out>
        mapelm = <optimized out>
#2  0x00007fa4f118ceb1 in ppb_url_loader_destroy (p=0x7fa4ed8c0810) at /home/francois/Downloads/freshplayerplugin/src/ppb_url_loader.c:81
        ul = 0x7fa4ed8c0810
#3  0x00007fa4f116b5e8 in pp_resource_unref (resource=3557) at /home/francois/Downloads/freshplayerplugin/src/pp_resource.c:202
        ref_cnt = 0
        ptr = 0x7fa4ed8c0810
#4  0x00007fa4f116b989 in ppb_core_release_resource (resource=3557) at /home/francois/Downloads/freshplayerplugin/src/ppb_core.c:46
#5  0x00007fa4ef783b6d in  () at /opt/google/chrome/PepperFlash/libpepflashplayer.so
#6  0x00007fa4ef76f91b in  () at /opt/google/chrome/PepperFlash/libpepflashplayer.so
#7  0x00007fa4ef7837ec in  () at /opt/google/chrome/PepperFlash/libpepflashplayer.so
#8  0x00007fa4ef783da9 in  () at /opt/google/chrome/PepperFlash/libpepflashplayer.so
#9  0x00007fa4ef783abb in  () at /opt/google/chrome/PepperFlash/libpepflashplayer.so
#10 0x00007fa4f115d4f8 in url_read_task_wrapper_comt (user_data=0x7fa4ed8862c0, result=0) at /home/francois/Downloads/freshplayerplugin/src/np_functions.c:845
        rt = 0x7fa4ed8862c0
#11 0x00007fa4f117ccdc in ppb_message_loop_run_int (message_loop=2, flags=2) at /home/francois/Downloads/freshplayerplugin/src/ppb_message_loop.c:321
        ccb = {func = 0x7fa4f115d4b3 <url_read_task_wrapper_comt>, user_data = 0x7fa4ed8862c0, flags = 0}
        now = {tv_sec = 1430823157, tv_nsec = 356711865}
        task = 0x7fa4edd39a40
        timeout = -11
        __func__ = "ppb_message_loop_run_int"
        ml = 0x7fa4ed89b670
        saved_state = {running = 0, teardown = 0}
        teardown = 0
        destroy_ml = 0
        depth = 1
        async_q = 0x7fa4ee46d840
        int_q = 0x7fa4ed8834e0
#12 0x00007fa4f117c89e in ppb_message_loop_run (message_loop=2) at /home/francois/Downloads/freshplayerplugin/src/ppb_message_loop.c:198
#13 0x00007fa4f11600b7 in fresh_wrapper_main_thread (p=0x7fa4fa5ab900) at /home/francois/Downloads/freshplayerplugin/src/main_thread.c:58
        pp_i = 0x7fa4fa5ab900
        message_loop = 2
        __func__ = "fresh_wrapper_main_thread"
#14 0x000000312f60752a in start_thread (arg=0x7fa4ec7fd700) at pthread_create.c:310
        __res = <optimized out>
        pd = 0x7fa4ec7fd700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140346319165184, -4337168127398935556, 140737263558656, 0, 140346319165184, 140346319165888, 4361332094958142460, -4346793525327199236}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
#15 0x000000312f30022d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```

Assembler dump:
```
$1 = 0x0
$2 = 0x0
rax            0x0      0
rbx            0x7fa4fa5f0000   140346551894016
rcx            0xd      13
rdx            0xffff2000       4294909952
rsi            0xd      13
rdi            0x7fa4fa5f0000   140346551894016
rbp            0x7fa4fa5f0c70   0x7fa4fa5f0c70
rsp            0x7fa4ec7fc768   0x7fa4ec7fc768
r8             0x7fa4fa500000   140346550910976
r9             0x44     68
r10            0x20     32
r11            0x0      0
r12            0xf0     240
r13            0x7fa4fa600040   140346551959616
r14            0x7fa4fa600048   140346551959624
r15            0x7fa4fa6007c8   140346551961544
rip            0x40ff90 0x40ff90 <jemalloc_crash>
eflags         0x10246  [ PF ZF IF RF ]
cs             0x33     51
ss             0x2b     43
ds             0x0      0
es             0x0      0
fs             0x0      0
gs             0x0      0
st0            0        (raw 0x00000000000000000000)
st1            0        (raw 0x00000000000000000000)
st2            0        (raw 0x00000000000000000000)
st3            0        (raw 0x00000000000000000000)
st4            4        (raw 0x40018000000000000000)
st5            4        (raw 0x40018000000000000000)
st6            12       (raw 0x4002c000000000000000)
st7            16       (raw 0x40038000000000000000)
fctrl          0x37f    895
fstat          0x0      0
ftag           0xffff   65535
fiseg          0x7fa4   32676
fioff          0xef7f4f9b       -276869221
foseg          0x7fa4   32676
fooff          0xec7fbbd8       -327173160
fop            0x0      0
mxcsr          0x1fa7   [ IE DE ZE PE IM DM ZM OM UM PM ]
ymm0           {v8_float = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v4_double = {0x8000000000000000, 0x8000000000000000, 0x0, 0x0}, v32_int8 = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0x0 <repeats 16 times>}, v16_int16 = {0x0, 0x0, 0x0, 0xff00, 0xffff, 0xffff, 0xffff, 0xffff, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v8_int32 = {0x0, 0xff000000, 0xffffffff, 0xffffffff, 0x0, 0x0, 0x0, 0x0}, v4_int64 = {0xff00000000000000, 0xffffffffffffffff, 0x0, 0x0}, v2_int128 = {0xffffffffffffffffff00000000000000, 0x00000000000000000000000000000000}}
ymm1           {v8_float = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v4_double = {0x0, 0x0, 0x0, 0x0}, v32_int8 = {0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0x0 <repeats 25 times>}, v16_int16 = {0xffff, 0xffff, 0xffff, 0xff, 0x0 <repeats 12 times>}, v8_int32 = {0xffffffff, 0xffffff, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v4_int64 = {0xffffffffffffff, 0x0, 0x0, 0x0}, v2_int128 = {0x000000000000000000ffffffffffffff, 0x00000000000000000000000000000000}}
ymm2           {v8_float = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v4_double = {0x0, 0x0, 0x0, 0x0}, v32_int8 = {0x61, 0x34, 0x33, 0x65, 0x61, 0x33, 0x63, 0x0 <repeats 25 times>}, v16_int16 = {0x3461, 0x6533, 0x3361, 0x63, 0x0 <repeats 12 times>}, v8_int32 = {0x65333461, 0x633361, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v4_int64 = {0x63336165333461, 0x0, 0x0, 0x0}, v2_int128 = {0x00000000000000000063336165333461, 0x00000000000000000000000000000000}}
ymm3           {v8_float = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v4_double = {0x8000000000000000, 0x8000000000000000, 0x0, 0x0}, v32_int8 = {0x32, 0x34, 0x33, 0x61, 0x31, 0x36, 0x30, 0x61, 0x38, 0x39, 0x37, 0x64, 0x63, 0x66, 0x35, 0x66, 0x0 <repeats 16 times>}, v16_int16 = {0x3432, 0x6133, 0x3631, 0x6130, 0x3938, 0x6437, 0x6663, 0x6635, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v8_int32 = {0x61333432, 0x61303631, 0x64373938, 0x66356663, 0x0, 0x0, 0x0, 0x0}, v4_int64 = {0x6130363161333432, 0x6635666364373938, 0x0, 0x0}, v2_int128 = {0x66356663643739386130363161333432, 0x00000000000000000000000000000000}}
ymm4           {v8_float = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v4_double = {0x8000000000000000, 0x8000000000000000, 0x0, 0x0}, v32_int8 = {0x62, 0x36, 0x33, 0x33, 0x63, 0x61, 0x35, 0x65, 0x32, 0x33, 0x38, 0x61, 0x35, 0x62, 0x33, 0x66, 0x0 <repeats 16 times>}, v16_int16 = {0x3662, 0x3333, 0x6163, 0x6535, 0x3332, 0x6138, 0x6235, 0x6633, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v8_int32 = {0x33333662, 0x65356163, 0x61383332, 0x66336235, 0x0, 0x0, 0x0, 0x0}, v4_int64 = {0x6535616333333662, 0x6633623561383332, 0x0, 0x0}, v2_int128 = {0x66336235613833326535616333333662, 0x00000000000000000000000000000000}}
ymm5           {v8_float = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v4_double = {0x0, 0x0, 0x0, 0x0}, v32_int8 = {0x32, 0x32, 0x32, 0x66, 0x61, 0x37, 0x37, 0x37, 0x37, 0x32, 0x65, 0x30, 0x31, 0x32, 0x36, 0x37, 0x0 <repeats 16 times>}, v16_int16 = {0x3232, 0x6632, 0x3761, 0x3737, 0x3237, 0x3065, 0x3231, 0x3736, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v8_int32 = {0x66323232, 0x37373761, 0x30653237, 0x37363231, 0x0, 0x0, 0x0, 0x0}, v4_int64 = {0x3737376166323232, 0x3736323130653237, 0x0, 0x0}, v2_int128 = {0x37363231306532373737376166323232, 0x00000000000000000000000000000000}}
ymm6           {v8_float = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v4_double = {0x8000000000000000, 0x0, 0x0, 0x0}, v32_int8 = {0x33, 0x39, 0x32, 0x36, 0x39, 0x35, 0x30, 0x64, 0x39, 0x35, 0x34, 0x64, 0x64, 0x34, 0x64, 0x30, 0x0 <repeats 16 times>}, v16_int16 = {0x3933, 0x3632, 0x3539, 0x6430, 0x3539, 0x6434, 0x3464, 0x3064, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v8_int32 = {0x36323933, 0x64303539, 0x64343539, 0x30643464, 0x0, 0x0, 0x0, 0x0}, v4_int64 = {0x6430353936323933, 0x3064346464343539, 0x0, 0x0}, v2_int128 = {0x30643464643435396430353936323933, 0x00000000000000000000000000000000}}
ymm7           {v8_float = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v4_double = {0x0, 0x0, 0x0, 0x0}, v32_int8 = {0x62, 0x63, 0x30, 0x65, 0x34, 0x31, 0x30, 0x30, 0x64, 0x33, 0x36, 0x65, 0x66, 0x39, 0x33, 0x39, 0x0 <repeats 16 times>}, v16_int16 = {0x6362, 0x6530, 0x3134, 0x3030, 0x3364, 0x6536, 0x3966, 0x3933, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v8_int32 = {0x65306362, 0x30303134, 0x65363364, 0x39333966, 0x0, 0x0, 0x0, 0x0}, v4_int64 = {0x3030313465306362, 0x3933396665363364, 0x0, 0x0}, v2_int128 = {0x39333966653633643030313465306362, 0x00000000000000000000000000000000}}
ymm8           {v8_float = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v4_double = {0x0, 0x0, 0x0, 0x0}, v32_int8 = {0x0 <repeats 32 times>}, v16_int16 = {0x0 <repeats 16 times>}, v8_int32 = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v4_int64 = {0x0, 0x0, 0x0, 0x0}, v2_int128 = {0x00000000000000000000000000000000, 0x00000000000000000000000000000000}}
ymm9           {v8_float = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v4_double = {0x0, 0x0, 0x0, 0x0}, v32_int8 = {0x37, 0x37, 0x32, 0x65, 0x30, 0x31, 0x32, 0x36, 0x37, 0x33, 0x39, 0x32, 0x36, 0x39, 0x35, 0x30, 0x0 <repeats 16 times>}, v16_int16 = {0x3737, 0x6532, 0x3130, 0x3632, 0x3337, 0x3239, 0x3936, 0x3035, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v8_int32 = {0x65323737, 0x36323130, 0x32393337, 0x30353936, 0x0, 0x0, 0x0, 0x0}, v4_int64 = {0x3632313065323737, 0x3035393632393337, 0x0, 0x0}, v2_int128 = {0x30353936323933373632313065323737, 0x00000000000000000000000000000000}}
ymm10          {v8_float = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v4_double = {0x8000000000000000, 0x0, 0x0, 0x0}, v32_int8 = {0x64, 0x39, 0x35, 0x34, 0x64, 0x64, 0x34, 0x64, 0x30, 0x62, 0x63, 0x30, 0x65, 0x34, 0x31, 0x30, 0x0 <repeats 16 times>}, v16_int16 = {0x3964, 0x3435, 0x6464, 0x6434, 0x6230, 0x3063, 0x3465, 0x3031, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v8_int32 = {0x34353964, 0x64346464, 0x30636230, 0x30313465, 0x0, 0x0, 0x0, 0x0}, v4_int64 = {0x6434646434353964, 0x3031346530636230, 0x0, 0x0}, v2_int128 = {0x30313465306362306434646434353964, 0x00000000000000000000000000000000}}
ymm11          {v8_float = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v4_double = {0x0, 0x8000000000000000, 0x0, 0x0}, v32_int8 = {0x30, 0x64, 0x33, 0x36, 0x65, 0x66, 0x39, 0x33, 0x39, 0x66, 0x39, 0x32, 0x61, 0x38, 0x66, 0x64, 0x0 <repeats 16 times>}, v16_int16 = {0x6430, 0x3633, 0x6665, 0x3339, 0x6639, 0x3239, 0x3861, 0x6466, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v8_int32 = {0x36336430, 0x33396665, 0x32396639, 0x64663861, 0x0, 0x0, 0x0, 0x0}, v4_int64 = {0x3339666536336430, 0x6466386132396639, 0x0, 0x0}, v2_int128 = {0x64663861323966393339666536336430, 0x00000000000000000000000000000000}}
ymm12          {v8_float = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v4_double = {0x0, 0x0, 0x0, 0x0}, v32_int8 = {0x65, 0x33, 0x62, 0x63, 0x33, 0x65, 0x66, 0x39, 0x63, 0x35, 0x34, 0x63, 0x35, 0x38, 0x63, 0x34, 0x0 <repeats 16 times>}, v16_int16 = {0x3365, 0x6362, 0x6533, 0x3966, 0x3563, 0x6334, 0x3835, 0x3463, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v8_int32 = {0x63623365, 0x39666533, 0x63343563, 0x34633835, 0x0, 0x0, 0x0, 0x0}, v4_int64 = {0x3966653363623365, 0x3463383563343563, 0x0, 0x0}, v2_int128 = {0x34633835633435633966653363623365, 0x00000000000000000000000000000000}}
ymm13          {v8_float = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v4_double = {0x0, 0x0, 0x0, 0x0}, v32_int8 = {0x36, 0x30, 0x61, 0x61, 0x63, 0x35, 0x64, 0x38, 0x64, 0x31, 0x64, 0x32, 0x66, 0x32, 0x30, 0x31, 0x0 <repeats 16 times>}, v16_int16 = {0x3036, 0x6161, 0x3563, 0x3864, 0x3164, 0x3264, 0x3266, 0x3130, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v8_int32 = {0x61613036, 0x38643563, 0x32643164, 0x31303266, 0x0, 0x0, 0x0, 0x0}, v4_int64 = {0x3864356361613036, 0x3130326632643164, 0x0, 0x0}, v2_int128 = {0x31303266326431643864356361613036, 0x00000000000000000000000000000000}}
ymm14          {v8_float = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v4_double = {0x0, 0x0, 0x0, 0x0}, v32_int8 = {0x61, 0x66, 0x31, 0x35, 0x35, 0x35, 0x61, 0x35, 0x37, 0x32, 0x34, 0x64, 0x62, 0x30, 0x33, 0x36, 0x0 <repeats 16 times>}, v16_int16 = {0x6661, 0x3531, 0x3535, 0x3561, 0x3237, 0x6434, 0x3062, 0x3633, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v8_int32 = {0x35316661, 0x35613535, 0x64343237, 0x36333062, 0x0, 0x0, 0x0, 0x0}, v4_int64 = {0x3561353535316661, 0x3633306264343237, 0x0, 0x0}, v2_int128 = {0x36333062643432373561353535316661, 0x00000000000000000000000000000000}}
ymm15          {v8_float = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v4_double = {0x0, 0x8000000000000000, 0x0, 0x0}, v32_int8 = {0x33, 0x35, 0x31, 0x34, 0x31, 0x37, 0x35, 0x39, 0x33, 0x61, 0x34, 0x33, 0x65, 0x61, 0x33, 0x63, 0x0 <repeats 16 times>}, v16_int16 = {0x3533, 0x3431, 0x3731, 0x3935, 0x6133, 0x3334, 0x6165, 0x6333, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v8_int32 = {0x34313533, 0x39353731, 0x33346133, 0x63336165, 0x0, 0x0, 0x0, 0x0}, v4_int64 = {0x3935373134313533, 0x6333616533346133, 0x0, 0x0}, v2_int128 = {0x63336165333461333935373134313533, 0x00000000000000000000000000000000}}
Dump of assembler code for function jemalloc_crash:
=> 0x000000000040ff90 <+0>:     movl   $0x0,0x0
   0x000000000040ff9b <+11>:    ud2    
End of assembler dump.
```

**Comment by i-rinat** [comment]
Does this happen often? I.e. how easy is it to reproduce?

**Comment by kubrickfr** [comment]
So far it is an isolated event but I haven't used it much today, I will comment here if it happens again.

**Comment by i-rinat** [comment]
Rare errors are the most annoying ones.

**Comment by kubrickfr** [comment]
Can't reproduce any more.
